set(CMAKE_LIBRARY_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../repos/boost_1_55_0/stage/lib)
set(CMAKE_INCLUDE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../repos/boost_1_55_0)
set(Boost_USE_STATIC_LIBS   ON)
set(Boost_USE_STATIC_RUNTIME ON)
set(Boost_USE_MULTITHREADED OFF)
message(STATUS ${CMAKE_LIBRARY_PATH})
find_package(Boost COMPONENTS program_options serialization system filesystem iostreams)

list(APPEND GenCMake_LIBRARIES ${Boost_LIBRARIES})

include_directories(${Boost_INCLUDE_DIRS})
set(CMAKE_LIBRARY_PATH ${CMAKE_SOURCE_DIR}/../karnagio/repos/zlib-1.2.8)
set(CMAKE_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/../karnagio/repos/zlib-1.2.8)

find_package( ZLIB REQUIRED )
if ( ZLIB_FOUND )
  message(STATUS ${ZLIB_LIBRARIES})
  include_directories( ${ZLIB_INCLUDE_DIRS} )
  list(APPEND GenCMake_LIBRARIES ${ZLIB_LIBRARIES})
endif( ZLIB_FOUND )
#add_definitions(-DBOOST_ALL_DYN_LINK)
