cmake_minimum_required(VERSION 2.8)
FIND_PACKAGE(PkgConfig)
#pkg_check_modules (PKGS)
include_directories (${PKGS_INCLUDE_DIRS}) 
INCLUDE(FindCURL) 
if (CURL_FOUND)
  list(APPEND GenCMake_LIBRARIES ${CURL_LIBRARIES})
  include_directories(${CURL_INCLUDE_DIRS})
endif(CURL_FOUND)
include(FindTinyXML.cmake NO_POLICY_SCOPE)
if (TINYXML_FOUND)
  list(APPEND GenCMake_LIBRARIES ${TINYXML_LIBRARIES})
  include_directories(${TNINYXML_INCLUDE_DIRS})
endif(TINYXML_FOUND)

