cmake_minimum_required(VERSION 2.8)
FIND_PACKAGE(XMLRPC QUIET COMPONENTS client)

if (DEFINED XMLRPC_LIBRARIES)
  list(REMOVE_ITEM XMLRPC_LIBRARIES XMLRPC_curl_LIBRARY-NOTFOUND)
  list(APPEND GenCMake_LIBRARIES
     ${XMLRPC_LIBRARIES} ) 
  include_directories(${XMLRPC_INCLUDE_DIRS})

  message(STATUS ${XMLRPC_LIBRARIES})
endif()
